# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
  - coolfire111111  # Replace with your GitHub username

custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
  - https://paypal.me/YOUR_PAYPAL_USERNAME  # Replace with your PayPal donation link
  - https://www.buymeacoffee.com/YOUR_USERNAME  # Replace with your Buy Me A Coffee link
  - https://buymeacoffee.com/nebula32 # Replace with your Buy Me A Coffee link
