# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
  - YOUR_GITHUB_USERNAME  # Replace with your GitHub username

patreon: # Replace with a single Patreon username
ko_fi: YOUR_KOFI_USERNAME # Replace with your Ko-fi username
tidelift: # Replace with a single Tidelift package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
  - https://paypal.me/YOUR_PAYPAL_USERNAME  # Replace with your PayPal donation link
  - https://www.buymeacoffee.com/YOUR_USERNAME  # Replace with your Buy Me A Coffee link
